[package]
name = "zeitrak-plugin-sdk"
version.workspace = true
edition.workspace = true

[dependencies]
# dioxus-extism-pdk = { git = "https://github.com/NavilaLabs/dioxus-extism", package = "dioxus-extism-pdk" }
paste             = "1"
serde             = { workspace = true }
serde_json        = { workspace = true }

[lints]
workspace = true
