use sea_orm_migration::prelude::*;

/// Seeds a "standard" role with non-administrative permissions for every existing
/// workspace that does not yet have one.
///
/// Writes only to projection tables (`projections__workspace_roles`,
/// `projections__workspace_role_permissions`). The event store is intentionally not
/// updated: `eventually-projection` uses `SqlCheckpoint` and projections are not
/// rebuilt from scratch on restart, so this approach is safe for existing deployments.
///
/// The operation is fully idempotent: running it on a workspace that already has a
/// "standard" role (e.g. one created via the application) is a no-op.
#[derive(DeriveMigrationName)]
pub struct Migration;

/// Fixed permission IDs for the standard role (seeded by earlier migrations).
const STANDARD_PERMISSION_IDS: &[&str] = &[
    "01100000-0000-7000-8000-000000000007", // timesheet.create
    "01100000-0000-7000-8000-000000000008", // timesheet.update
    "01100000-0000-7000-8000-000000000009", // timesheet.export
    "01100000-0000-7000-8000-00000000000e", // timesheet.cancel
];

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        let db = manager.get_database_backend();
        let conn = manager.get_connection();

        // Step 1: Insert a "standard" role for each workspace that does not already have one.
        // UUID is generated by the database (randomblob on SQLite, gen_random_uuid on Postgres).
        let role_insert = if db == sea_orm::DatabaseBackend::Sqlite {
            "INSERT OR IGNORE INTO projections__workspace_roles (id, workspace_id, name)
             SELECT lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-'
                 || lower(hex(randomblob(2))) || '-' || lower(hex(randomblob(2))) || '-'
                 || lower(hex(randomblob(6))),
                    w.id,
                    'standard'
             FROM projections__workspaces w
             WHERE NOT EXISTS (
                 SELECT 1 FROM projections__workspace_roles r
                 WHERE r.workspace_id = w.id AND r.name = 'standard'
             )"
            .to_string()
        } else {
            "INSERT INTO projections__workspace_roles (id, workspace_id, name)
             SELECT gen_random_uuid(), w.id, 'standard'
             FROM projections__workspaces w
             WHERE NOT EXISTS (
                 SELECT 1 FROM projections__workspace_roles r
                 WHERE r.workspace_id = w.id AND r.name = 'standard'
             )
             ON CONFLICT (id) DO NOTHING"
                .to_string()
        };
        conn.execute_unprepared(&role_insert).await?;

        // Step 2: Assign the 6 standard permissions to all "standard" roles.
        // Only assigns permissions that are actually present in the permissions table
        // (guards against running this migration before the permission seed migration).
        let perm_insert = if db == sea_orm::DatabaseBackend::Sqlite {
            let perm_values = STANDARD_PERMISSION_IDS
                .iter()
                .map(|id| format!("SELECT '{id}' AS pid"))
                .collect::<Vec<_>>()
                .join(" UNION ALL ");
            format!(
                "INSERT OR IGNORE INTO projections__workspace_role_permissions (workspace_role_id, permission_id)
                 SELECT r.id, p.pid
                 FROM projections__workspace_roles r
                 CROSS JOIN ({perm_values}) AS p
                 WHERE r.name = 'standard'
                   AND EXISTS (SELECT 1 FROM permissions WHERE id = p.pid)"
            )
        } else {
            let perm_values = STANDARD_PERMISSION_IDS
                .iter()
                .map(|id| format!("SELECT '{id}' AS pid"))
                .collect::<Vec<_>>()
                .join(" UNION ALL ");
            format!(
                "INSERT INTO projections__workspace_role_permissions (workspace_role_id, permission_id)
                 SELECT r.id, p.pid
                 FROM projections__workspace_roles r
                 CROSS JOIN ({perm_values}) AS p
                 WHERE r.name = 'standard'
                   AND EXISTS (SELECT 1 FROM permissions WHERE id = p.pid)
                 ON CONFLICT (workspace_role_id, permission_id) DO NOTHING"
            )
        };
        conn.execute_unprepared(&perm_insert).await?;

        Ok(())
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        let conn = manager.get_connection();

        // Remove the 6 standard permission assignments from all "standard" roles.
        let perm_ids = STANDARD_PERMISSION_IDS
            .iter()
            .map(|id| format!("'{id}'"))
            .collect::<Vec<_>>()
            .join(", ");

        conn.execute_unprepared(&format!(
            "DELETE FROM projections__workspace_role_permissions
             WHERE workspace_role_id IN (
                 SELECT id FROM projections__workspace_roles WHERE name = 'standard'
             )
             AND permission_id IN ({perm_ids})"
        ))
        .await?;

        // Remove "standard" roles that have no remaining permission assignments
        // (i.e. those that were seeded by this migration and not further customised).
        conn.execute_unprepared(
            "DELETE FROM projections__workspace_roles
             WHERE name = 'standard'
               AND id NOT IN (
                   SELECT workspace_role_id FROM projections__workspace_role_permissions
               )",
        )
        .await?;

        Ok(())
    }
}
