application:
  environment: development
  name: Zeitrak
  project_root: /workspaces/zeitrak
  base_url: "http://localhost:8080"
  security:
    invite_only: false
    invite_token_expiry_secs: 300
  smtp:
    host: localhost
    port: 1025
    from_address: noreply@zeitrak.app
