application:
  environment: develop
  name: Zeitrak
  project_root: ${ZK_PROJECT_ROOT}

  security:
    authentication_secret: ${ZK_AUTHENTICATION_SECRET}
    # invite_only: ${APP_INVITE_ONLY}
    # invite_token_expiry: ${ZK_INVITE_TOKEN_EXPIRY}
